[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[hooks.yapf]
priority = 30

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort]
priority = 50

[hooks.isort.kwargs]
indent = "		"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "apeye",
    "atomicwrites",
    "attrs",
    "cawdrey",
    "coincidence",
    "colorama",
    "consolekit",
    "coverage",
    "coverage_pyver_pragma",
    "domdf_python_tools",
    "first",
    "flake8",
    "handy_archives",
    "hpy",
    "httpx",
    "importlib_metadata",
    "packaging",
    "pypi_json",
    "pytest",
    "pytest_cov",
    "pytest_randomly",
    "pytest_rerunfailures",
    "pytest_timeout",
    "pytz",
    "shippinglabel",
    "sphinx",
    "wheel",
]
known_first_party = [ "dist_meta",]

[config]
indent = "	"
line_length = 115
